### ISSUE TITLE
Simplify on-boarding process for new users

### ISSUE THREAD

**Issue by quentinlesceller** [mimblewimble/site#127]
Meta issue to track the simplification of the on-boarding process.
1. Create release page https://github.com/mimblewimble/site/issues/103. With possibly Keybase signed release.
1. Create a page similar to https://bitcoin.org/en/choose-your-wallet. Listing third party wallet/implementations (must be open source) with a disclaimer.
1. Avoid going on GitHub as much as possible.

Note that 1. and 2. can be combined.

**Comment by quentinlesceller** [comment]
Add a get started page similar to https://z.cash/get-started/

**Comment by CircusDad** [comment]
It looks like someone is working this and it looks great (https://grin.mw/get-started).  However, wanted to caution that it might be unwise to have a prominent link on the website go to an un-moderated wiki page (Buy Grin --> https://github.com/mimblewimble/docs/wiki/Community-projects#exchanges).  I would have created a pull request with a suggested solutions... but I can't think of a better solution right now because the way it was done makes sense... it just exposes the site to abuse.  When people land on a wiki they should know right away they are headed to a wiki.

**Comment by lehnberg** [comment]
I'm considering this fixed for now, with further improvements welcomed in new PRs and issues. Closing
